### PR TITLE
chore: add standardjs, lint / fix, and update gh actions

### LINKED ISSUE #44: Add eslint
There are `eslint-disable-line`'s everywhere in the code but currently no eslint setup or config is in the repository.

### PR DESCRIPTION
**Pull request by ParamagicDev**
## Status

Ready

## Description

- Uses Standard to lint Javascript
- Updates GH actions with linting and caching
- add lint / fix scripts
- add node 15.x to gh actions

## Related issues

Fixes #44

### CODE REVIEW

File: src/HoneybadgerSourceMapPlugin.js [hunk 1]
```diff
@@ -1,135 +1,133 @@
...
     }
   }
 
-  getAssets(compilation) {
-    const { chunks } = compilation.getStats().toJson();
+  getAssets (compilation) {
+    const { chunks } = compilation.getStats().toJson()
 
     return reduce(chunks, (result, chunk) => {
-      const chunkName = chunk.names[0];
```
Comment (ParamagicDev) [inline src/HoneybadgerSourceMapPlugin.js:66]: This was fully deleted. It was an unused variable.

**Review by joshuap — APPROVED** [review]
:shipit:
